name: Accessibility Scanner
permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write
on:
  workflow_dispatch:
  push:
    branches: max/a11y-scanner

jobs:
  accessibility_scanner:
    name: Run accessibility scanner
    runs-on: ubuntu-latest
    steps:
      - uses: github/accessibility-scanner@v2
        with:
          urls: |
            https://cds.coinbase.com
          repository: coinbase/cds
          token: ${{ secrets.GH_TOKEN }}
          cache_key: coinbase.com
          skip_copilot_assignment: true
          include_screenshots: true
